# Generated by Django 2.2.6 on 2020-02-13 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_ID', models.PositiveIntegerField()),
                ('train_no', models.PositiveIntegerField()),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('seal_status', models.BooleanField()),
                ('parcels', models.PositiveIntegerField()),
                ('station1', models.CharField(max_length=10)),
                ('station2', models.CharField(max_length=10)),
                ('station3', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 13, 8, 31, 17, 926534, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
    ]
