# Generated by Django 2.2.6 on 2020-02-20 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 16, 49, 30, 33150, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Otp',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 16, 49, 30, 33150, tzinfo=utc)),
        ),
    ]
