# Generated by Django 2.2.6 on 2020-02-20 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20200220_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 3, 46, 876734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 3, 46, 877734, tzinfo=utc)),
        ),
    ]
