# Generated by Django 2.2.6 on 2020-02-13 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
                ('total_train', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.PositiveIntegerField(default=False)),
                ('train_from', models.CharField(max_length=50)),
                ('train_to', models.CharField(max_length=50)),
                ('station1', models.CharField(default=0, max_length=50)),
                ('station2', models.CharField(default=0, max_length=50)),
                ('station3', models.CharField(default=0, max_length=50)),
                ('station4', models.CharField(default=0, max_length=50)),
                ('station5', models.CharField(default=0, max_length=50)),
                ('station6', models.CharField(default=0, max_length=50)),
                ('station7', models.CharField(default=0, max_length=50)),
                ('station8', models.CharField(default=0, max_length=50)),
                ('station9', models.CharField(default=0, max_length=50)),
                ('station10', models.CharField(default=0, max_length=50)),
                ('station11', models.CharField(default=0, max_length=50)),
                ('station12', models.CharField(default=0, max_length=50)),
                ('station13', models.CharField(default=0, max_length=50)),
                ('station14', models.CharField(default=0, max_length=50)),
                ('station15', models.CharField(default=0, max_length=50)),
                ('station16', models.CharField(default=0, max_length=50)),
                ('station17', models.CharField(default=0, max_length=50)),
                ('station18', models.CharField(default=0, max_length=50)),
                ('station19', models.CharField(default=0, max_length=50)),
                ('station20', models.CharField(default=0, max_length=50)),
                ('train_live_station', models.CharField(default=0, max_length=50)),
                ('train_days', models.CharField(max_length=50)),
                ('train_from_time', models.TimeField(default=datetime.datetime(2020, 2, 13, 8, 31, 4, 322370, tzinfo=utc))),
                ('train_to_time', models.TimeField(default=datetime.datetime(2020, 2, 13, 8, 31, 4, 322370, tzinfo=utc))),
            ],
        ),
    ]
