# Generated by Django 2.2.6 on 2020-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='done_date',
            field=models.DateTimeField(null=True),
        ),
    ]
