# Generated by Django 2.2.6 on 2020-02-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_ID', models.PositiveIntegerField()),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('seal_status', models.BooleanField()),
                ('parcel_status', models.BooleanField()),
            ],
        ),
    ]
